language: c
compiler:
  - gcc
script:
  - make clean
  - make
git:
  depth: 5

addons:
  apt:
    packages:
      - &base_deps
        - libwebkit2gtk-4.0-dev
        - libgtk-3-dev
        - libgcr-3-dev
        - libx11-dev

